# Generated by Django 4.1.7 on 2023-03-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=3000)),
                ('todo_list', models.CharField(max_length=3000)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
