# Generated by Django 4.1.7 on 2023-03-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_list_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
